Drop table if exists providers
Create table providers (
   Id  VARCHAR(50) )
   ORGANIZATION  VARCHAR(50) )
   NAME  VARCHAR(50) )
   GENDER  VARCHAR(50) )
   SPECIALITY  VARCHAR(50) )
   ADDRESS  VARCHAR(50) )
   CITY  VARCHAR(50) )
   STATE  VARCHAR(50) )
   ZIP  VARCHAR(50) )
   LAT  VARCHAR(50) )
   LON  VARCHAR(50) )
   UTILIZATION  VARCHAR(50) )
   COUNTY
  VARCHAR(50) )
);