## creates schema for TPC-DS (Data Warehouse) and loads sample data
##
## NOTE: script will DROP existing tables before creating new ones
##
## NOTE2: loading data from local csv is turned OFF by defult on mysql on mac
##
##   server side
##      SHOW GLOBAL VARIABLES LIKE 'local_infile';
##      SET GLOBAL local_infile=1;
##   client side
##      mysql --local-infile=1
##

DROP DATABASE IF EXISTS tpcds;
CREATE DATABASE IF NOT EXISTS tpcds;
USE tpcds;

CREATE TABLE `date_dim` (
  `d_date_sk` int NOT NULL,
  `d_date_id` char(16) NOT NULL,
  `d_date` date DEFAULT NULL,
  `d_month_seq` int DEFAULT NULL,
  `d_week_seq` int DEFAULT NULL,
  `d_quarter_seq` int DEFAULT NULL,
  `d_year` int DEFAULT NULL,
  `d_dow` int DEFAULT NULL,
  `d_moy` int DEFAULT NULL,
  `d_dom` int DEFAULT NULL,
  `d_qoy` int DEFAULT NULL,
  `d_fy_year` int DEFAULT NULL,
  `d_fy_quarter_seq` int DEFAULT NULL,
  `d_fy_week_seq` int DEFAULT NULL,
  `d_day_name` char(9) DEFAULT NULL,
  `d_quarter_name` char(6) DEFAULT NULL,
  `d_holiday` char(1) DEFAULT NULL,
  `d_weekend` char(1) DEFAULT NULL,
  `d_following_holiday` char(1) DEFAULT NULL,
  `d_first_dom` int DEFAULT NULL,
  `d_last_dom` int DEFAULT NULL,
  `d_same_day_ly` int DEFAULT NULL,
  `d_same_day_lq` int DEFAULT NULL,
  `d_current_day` char(1) DEFAULT NULL,
  `d_current_week` char(1) DEFAULT NULL,
  `d_current_month` char(1) DEFAULT NULL,
  `d_current_quarter` char(1) DEFAULT NULL,
  `d_current_year` char(1) DEFAULT NULL,
  PRIMARY KEY (`d_date_sk`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `call_center` (
  `cc_call_center_sk` int NOT NULL,
  `cc_call_center_id` char(16) NOT NULL,
  `cc_rec_start_date` date DEFAULT NULL,
  `cc_rec_end_date` date DEFAULT NULL,
  `cc_closed_date_sk` int DEFAULT NULL,
  `cc_open_date_sk` int DEFAULT NULL,
  `cc_name` varchar(50) DEFAULT NULL,
  `cc_class` varchar(50) DEFAULT NULL,
  `cc_employees` int DEFAULT NULL,
  `cc_sq_ft` int DEFAULT NULL,
  `cc_hours` char(20) DEFAULT NULL,
  `cc_manager` varchar(40) DEFAULT NULL,
  `cc_mkt_id` int DEFAULT NULL,
  `cc_mkt_class` char(50) DEFAULT NULL,
  `cc_mkt_desc` varchar(100) DEFAULT NULL,
  `cc_market_manager` varchar(40) DEFAULT NULL,
  `cc_division` int DEFAULT NULL,
  `cc_division_name` varchar(50) DEFAULT NULL,
  `cc_company` int DEFAULT NULL,
  `cc_company_name` char(50) DEFAULT NULL,
  `cc_street_number` char(10) DEFAULT NULL,
  `cc_street_name` varchar(60) DEFAULT NULL,
  `cc_street_type` char(15) DEFAULT NULL,
  `cc_suite_number` char(10) DEFAULT NULL,
  `cc_city` varchar(60) DEFAULT NULL,
  `cc_county` varchar(30) DEFAULT NULL,
  `cc_state` char(2) DEFAULT NULL,
  `cc_zip` char(10) DEFAULT NULL,
  `cc_country` varchar(20) DEFAULT NULL,
  `cc_gmt_offset` decimal(5,2) DEFAULT NULL,
  `cc_tax_percentage` decimal(5,2) DEFAULT NULL,
  PRIMARY KEY (`cc_call_center_sk`),
  KEY `cc_d2` (`cc_open_date_sk`),
  KEY `cc_d1` (`cc_closed_date_sk`),
  CONSTRAINT `cc_d1` FOREIGN KEY (`cc_closed_date_sk`) REFERENCES `date_dim` (`d_date_sk`),
  CONSTRAINT `cc_d2` FOREIGN KEY (`cc_open_date_sk`) REFERENCES `date_dim` (`d_date_sk`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `catalog_page` (
  `cp_catalog_page_sk` int NOT NULL,
  `cp_catalog_page_id` char(16) NOT NULL,
  `cp_start_date_sk` int DEFAULT NULL,
  `cp_end_date_sk` int DEFAULT NULL,
  `cp_department` varchar(50) DEFAULT NULL,
  `cp_catalog_number` int DEFAULT NULL,
  `cp_catalog_page_number` int DEFAULT NULL,
  `cp_description` varchar(100) DEFAULT NULL,
  `cp_type` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`cp_catalog_page_sk`),
  KEY `cp_d2` (`cp_start_date_sk`),
  KEY `cp_d1` (`cp_end_date_sk`),
  CONSTRAINT `cp_d1` FOREIGN KEY (`cp_end_date_sk`) REFERENCES `date_dim` (`d_date_sk`),
  CONSTRAINT `cp_d2` FOREIGN KEY (`cp_start_date_sk`) REFERENCES `date_dim` (`d_date_sk`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `customer_address` (
  `ca_address_sk` int NOT NULL,
  `ca_address_id` char(16) NOT NULL,
  `ca_street_number` char(10) DEFAULT NULL,
  `ca_street_name` varchar(60) DEFAULT NULL,
  `ca_street_type` char(15) DEFAULT NULL,
  `ca_suite_number` char(10) DEFAULT NULL,
  `ca_city` varchar(60) DEFAULT NULL,
  `ca_county` varchar(30) DEFAULT NULL,
  `ca_state` char(2) DEFAULT NULL,
  `ca_zip` char(10) DEFAULT NULL,
  `ca_country` varchar(20) DEFAULT NULL,
  `ca_gmt_offset` decimal(5,2) DEFAULT NULL,
  `ca_location_type` char(20) DEFAULT NULL,
  PRIMARY KEY (`ca_address_sk`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `customer_demographics` (
  `cd_demo_sk` int NOT NULL,
  `cd_gender` char(1) DEFAULT NULL,
  `cd_marital_status` char(1) DEFAULT NULL,
  `cd_education_status` char(20) DEFAULT NULL,
  `cd_purchase_estimate` int DEFAULT NULL,
  `cd_credit_rating` char(10) DEFAULT NULL,
  `cd_dep_count` int DEFAULT NULL,
  `cd_dep_employed_count` int DEFAULT NULL,
  `cd_dep_college_count` int DEFAULT NULL,
  PRIMARY KEY (`cd_demo_sk`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `income_band` (
  `ib_income_band_sk` int NOT NULL,
  `ib_lower_bound` int DEFAULT NULL,
  `ib_upper_bound` int DEFAULT NULL,
  PRIMARY KEY (`ib_income_band_sk`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `household_demographics` (
  `hd_demo_sk` int NOT NULL,
  `hd_income_band_sk` int DEFAULT NULL,
  `hd_buy_potential` char(15) DEFAULT NULL,
  `hd_dep_count` int DEFAULT NULL,
  `hd_vehicle_count` int DEFAULT NULL,
  PRIMARY KEY (`hd_demo_sk`),
  KEY `hd_ib` (`hd_income_band_sk`),
  CONSTRAINT `hd_ib` FOREIGN KEY (`hd_income_band_sk`) REFERENCES `income_band` (`ib_income_band_sk`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `customer` (
  `c_customer_sk` int NOT NULL,
  `c_customer_id` char(16) NOT NULL,
  `c_current_cdemo_sk` int DEFAULT NULL,
  `c_current_hdemo_sk` int DEFAULT NULL,
  `c_current_addr_sk` int DEFAULT NULL,
  `c_first_shipto_date_sk` int DEFAULT NULL,
  `c_first_sales_date_sk` int DEFAULT NULL,
  `c_salutation` char(10) DEFAULT NULL,
  `c_first_name` char(20) DEFAULT NULL,
  `c_last_name` char(30) DEFAULT NULL,
  `c_preferred_cust_flag` char(1) DEFAULT NULL,
  `c_birth_day` int DEFAULT NULL,
  `c_birth_month` int DEFAULT NULL,
  `c_birth_year` int DEFAULT NULL,
  `c_birth_country` varchar(20) DEFAULT NULL,
  `c_login` char(13) DEFAULT NULL,
  `c_email_address` char(50) DEFAULT NULL,
  `c_last_review_date` char(10) DEFAULT NULL,
  PRIMARY KEY (`c_customer_sk`),
  KEY `c_fsd2` (`c_first_shipto_date_sk`),
  KEY `c_fsd` (`c_first_sales_date_sk`),
  KEY `c_hd` (`c_current_hdemo_sk`),
  KEY `c_cd` (`c_current_cdemo_sk`),
  KEY `c_a` (`c_current_addr_sk`),
  CONSTRAINT `c_a` FOREIGN KEY (`c_current_addr_sk`) REFERENCES `customer_address` (`ca_address_sk`),
  CONSTRAINT `c_cd` FOREIGN KEY (`c_current_cdemo_sk`) REFERENCES `customer_demographics` (`cd_demo_sk`),
  CONSTRAINT `c_fsd` FOREIGN KEY (`c_first_sales_date_sk`) REFERENCES `date_dim` (`d_date_sk`),
  CONSTRAINT `c_fsd2` FOREIGN KEY (`c_first_shipto_date_sk`) REFERENCES `date_dim` (`d_date_sk`),
  CONSTRAINT `c_hd` FOREIGN KEY (`c_current_hdemo_sk`) REFERENCES `household_demographics` (`hd_demo_sk`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `item` (
  `i_item_sk` int NOT NULL,
  `i_item_id` char(16) NOT NULL,
  `i_rec_start_date` date DEFAULT NULL,
  `i_rec_end_date` date DEFAULT NULL,
  `i_item_desc` varchar(200) DEFAULT NULL,
  `i_current_price` decimal(7,2) DEFAULT NULL,
  `i_wholesale_cost` decimal(7,2) DEFAULT NULL,
  `i_brand_id` int DEFAULT NULL,
  `i_brand` char(50) DEFAULT NULL,
  `i_class_id` int DEFAULT NULL,
  `i_class` char(50) DEFAULT NULL,
  `i_category_id` int DEFAULT NULL,
  `i_category` char(50) DEFAULT NULL,
  `i_manufact_id` int DEFAULT NULL,
  `i_manufact` char(50) DEFAULT NULL,
  `i_size` char(20) DEFAULT NULL,
  `i_formulation` char(20) DEFAULT NULL,
  `i_color` char(20) DEFAULT NULL,
  `i_units` char(10) DEFAULT NULL,
  `i_container` char(10) DEFAULT NULL,
  `i_manager_id` int DEFAULT NULL,
  `i_product_name` char(50) DEFAULT NULL,
  PRIMARY KEY (`i_item_sk`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `warehouse` (
  `w_warehouse_sk` int(11) NOT NULL,
  `w_warehouse_id` char(16) NOT NULL,
  `w_warehouse_name` varchar(20) DEFAULT NULL,
  `w_warehouse_sq_ft` int(11) DEFAULT NULL,
  `w_street_number` char(10) DEFAULT NULL,
  `w_street_name` varchar(60) DEFAULT NULL,
  `w_street_type` char(15) DEFAULT NULL,
  `w_suite_number` char(10) DEFAULT NULL,
  `w_city` varchar(60) DEFAULT NULL,
  `w_county` varchar(30) DEFAULT NULL,
  `w_state` char(2) DEFAULT NULL,
  `w_zip` char(10) DEFAULT NULL,
  `w_country` varchar(20) DEFAULT NULL,
  `w_gmt_offset` decimal(5,2) DEFAULT NULL,
  PRIMARY KEY (`w_warehouse_sk`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `inventory` (
  `inv_date_sk` int NOT NULL,
  `inv_item_sk` int NOT NULL,
  `inv_warehouse_sk` int NOT NULL,
  `inv_quantity_on_hand` int DEFAULT NULL,
  PRIMARY KEY (`inv_date_sk`,`inv_item_sk`,`inv_warehouse_sk`),
  KEY `inv_w` (`inv_warehouse_sk`),
  KEY `inv_i` (`inv_item_sk`),
  CONSTRAINT `inv_d` FOREIGN KEY (`inv_date_sk`) REFERENCES `date_dim` (`d_date_sk`),
  CONSTRAINT `inv_i` FOREIGN KEY (`inv_item_sk`) REFERENCES `item` (`i_item_sk`),
  CONSTRAINT `inv_w` FOREIGN KEY (`inv_warehouse_sk`) REFERENCES `warehouse` (`w_warehouse_sk`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `promotion` (
  `p_promo_sk` int NOT NULL,
  `p_promo_id` char(16) NOT NULL,
  `p_start_date_sk` int DEFAULT NULL,
  `p_end_date_sk` int DEFAULT NULL,
  `p_item_sk` int DEFAULT NULL,
  `p_cost` decimal(15,2) DEFAULT NULL,
  `p_response_target` int DEFAULT NULL,
  `p_promo_name` char(50) DEFAULT NULL,
  `p_channel_dmail` char(1) DEFAULT NULL,
  `p_channel_email` char(1) DEFAULT NULL,
  `p_channel_catalog` char(1) DEFAULT NULL,
  `p_channel_tv` char(1) DEFAULT NULL,
  `p_channel_radio` char(1) DEFAULT NULL,
  `p_channel_press` char(1) DEFAULT NULL,
  `p_channel_event` char(1) DEFAULT NULL,
  `p_channel_demo` char(1) DEFAULT NULL,
  `p_channel_details` varchar(100) DEFAULT NULL,
  `p_purpose` char(15) DEFAULT NULL,
  `p_discount_active` char(1) DEFAULT NULL,
  PRIMARY KEY (`p_promo_sk`),
  KEY `p_start_date` (`p_start_date_sk`),
  KEY `p_i` (`p_item_sk`),
  KEY `p_end_date` (`p_end_date_sk`),
  CONSTRAINT `p_end_date` FOREIGN KEY (`p_end_date_sk`) REFERENCES `date_dim` (`d_date_sk`),
  CONSTRAINT `p_i` FOREIGN KEY (`p_item_sk`) REFERENCES `item` (`i_item_sk`),
  CONSTRAINT `p_start_date` FOREIGN KEY (`p_start_date_sk`) REFERENCES `date_dim` (`d_date_sk`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `reason` (
  `r_reason_sk` int NOT NULL,
  `r_reason_id` char(16) NOT NULL,
  `r_reason_desc` char(100) DEFAULT NULL,
  PRIMARY KEY (`r_reason_sk`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `ship_mode` (
  `sm_ship_mode_sk` int NOT NULL,
  `sm_ship_mode_id` char(16) NOT NULL,
  `sm_type` char(30) DEFAULT NULL,
  `sm_code` char(10) DEFAULT NULL,
  `sm_carrier` char(20) DEFAULT NULL,
  `sm_contract` char(20) DEFAULT NULL,
  PRIMARY KEY (`sm_ship_mode_sk`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `store` (
  `s_store_sk` int NOT NULL,
  `s_store_id` char(16) NOT NULL,
  `s_rec_start_date` date DEFAULT NULL,
  `s_rec_end_date` date DEFAULT NULL,
  `s_closed_date_sk` int DEFAULT NULL,
  `s_store_name` varchar(50) DEFAULT NULL,
  `s_number_employees` int DEFAULT NULL,
  `s_floor_space` int DEFAULT NULL,
  `s_hours` char(20) DEFAULT NULL,
  `s_manager` varchar(40) DEFAULT NULL,
  `s_market_id` int DEFAULT NULL,
  `s_geography_class` varchar(100) DEFAULT NULL,
  `s_market_desc` varchar(100) DEFAULT NULL,
  `s_market_manager` varchar(40) DEFAULT NULL,
  `s_division_id` int DEFAULT NULL,
  `s_division_name` varchar(50) DEFAULT NULL,
  `s_company_id` int DEFAULT NULL,
  `s_company_name` varchar(50) DEFAULT NULL,
  `s_street_number` varchar(10) DEFAULT NULL,
  `s_street_name` varchar(60) DEFAULT NULL,
  `s_street_type` char(15) DEFAULT NULL,
  `s_suite_number` char(10) DEFAULT NULL,
  `s_city` varchar(60) DEFAULT NULL,
  `s_county` varchar(30) DEFAULT NULL,
  `s_state` char(2) DEFAULT NULL,
  `s_zip` char(10) DEFAULT NULL,
  `s_country` varchar(20) DEFAULT NULL,
  `s_gmt_offset` decimal(5,2) DEFAULT NULL,
  `s_tax_precentage` decimal(5,2) DEFAULT NULL,
  PRIMARY KEY (`s_store_sk`),
  KEY `s_close_date` (`s_closed_date_sk`),
  CONSTRAINT `s_close_date` FOREIGN KEY (`s_closed_date_sk`) REFERENCES `date_dim` (`d_date_sk`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `time_dim` (
  `t_time_sk` int NOT NULL,
  `t_time_id` char(16) NOT NULL,
  `t_time` int DEFAULT NULL,
  `t_hour` int DEFAULT NULL,
  `t_minute` int DEFAULT NULL,
  `t_second` int DEFAULT NULL,
  `t_am_pm` char(2) DEFAULT NULL,
  `t_shift` char(20) DEFAULT NULL,
  `t_sub_shift` char(20) DEFAULT NULL,
  `t_meal_time` char(20) DEFAULT NULL,
  PRIMARY KEY (`t_time_sk`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `store_returns` (
  `sr_returned_date_sk` int DEFAULT NULL,
  `sr_return_time_sk` int DEFAULT NULL,
  `sr_item_sk` int NOT NULL,
  `sr_customer_sk` int DEFAULT NULL,
  `sr_cdemo_sk` int DEFAULT NULL,
  `sr_hdemo_sk` int DEFAULT NULL,
  `sr_addr_sk` int DEFAULT NULL,
  `sr_store_sk` int DEFAULT NULL,
  `sr_reason_sk` int DEFAULT NULL,
  `sr_ticket_number` int NOT NULL,
  `sr_return_quantity` int DEFAULT NULL,
  `sr_return_amt` decimal(7,2) DEFAULT NULL,
  `sr_return_tax` decimal(7,2) DEFAULT NULL,
  `sr_return_amt_inc_tax` decimal(7,2) DEFAULT NULL,
  `sr_fee` decimal(7,2) DEFAULT NULL,
  `sr_return_ship_cost` decimal(7,2) DEFAULT NULL,
  `sr_refunded_cash` decimal(7,2) DEFAULT NULL,
  `sr_reversed_charge` decimal(7,2) DEFAULT NULL,
  `sr_store_credit` decimal(7,2) DEFAULT NULL,
  `sr_net_loss` decimal(7,2) DEFAULT NULL,
  PRIMARY KEY (`sr_item_sk`,`sr_ticket_number`),
  KEY `sr_s` (`sr_store_sk`),
  KEY `sr_t` (`sr_return_time_sk`),
  KEY `sr_ret_d` (`sr_returned_date_sk`),
  KEY `sr_r` (`sr_reason_sk`),
  KEY `sr_hd` (`sr_hdemo_sk`),
  KEY `sr_c` (`sr_customer_sk`),
  KEY `sr_cd` (`sr_cdemo_sk`),
  KEY `sr_a` (`sr_addr_sk`),
  CONSTRAINT `sr_a` FOREIGN KEY (`sr_addr_sk`) REFERENCES `customer_address` (`ca_address_sk`),
  CONSTRAINT `sr_c` FOREIGN KEY (`sr_customer_sk`) REFERENCES `customer` (`c_customer_sk`),
  CONSTRAINT `sr_cd` FOREIGN KEY (`sr_cdemo_sk`) REFERENCES `customer_demographics` (`cd_demo_sk`),
  CONSTRAINT `sr_hd` FOREIGN KEY (`sr_hdemo_sk`) REFERENCES `household_demographics` (`hd_demo_sk`),
  CONSTRAINT `sr_i` FOREIGN KEY (`sr_item_sk`) REFERENCES `item` (`i_item_sk`),
  CONSTRAINT `sr_r` FOREIGN KEY (`sr_reason_sk`) REFERENCES `reason` (`r_reason_sk`),
  CONSTRAINT `sr_ret_d` FOREIGN KEY (`sr_returned_date_sk`) REFERENCES `date_dim` (`d_date_sk`),
  CONSTRAINT `sr_s` FOREIGN KEY (`sr_store_sk`) REFERENCES `store` (`s_store_sk`),
  CONSTRAINT `sr_t` FOREIGN KEY (`sr_return_time_sk`) REFERENCES `time_dim` (`t_time_sk`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `store_sales` (
  `ss_sold_date_sk` int DEFAULT NULL,
  `ss_sold_time_sk` int DEFAULT NULL,
  `ss_item_sk` int NOT NULL,
  `ss_customer_sk` int DEFAULT NULL,
  `ss_cdemo_sk` int DEFAULT NULL,
  `ss_hdemo_sk` int DEFAULT NULL,
  `ss_addr_sk` int DEFAULT NULL,
  `ss_store_sk` int DEFAULT NULL,
  `ss_promo_sk` int DEFAULT NULL,
  `ss_ticket_number` int NOT NULL,
  `ss_quantity` int DEFAULT NULL,
  `ss_wholesale_cost` decimal(7,2) DEFAULT NULL,
  `ss_list_price` decimal(7,2) DEFAULT NULL,
  `ss_sales_price` decimal(7,2) DEFAULT NULL,
  `ss_ext_discount_amt` decimal(7,2) DEFAULT NULL,
  `ss_ext_sales_price` decimal(7,2) DEFAULT NULL,
  `ss_ext_wholesale_cost` decimal(7,2) DEFAULT NULL,
  `ss_ext_list_price` decimal(7,2) DEFAULT NULL,
  `ss_ext_tax` decimal(7,2) DEFAULT NULL,
  `ss_coupon_amt` decimal(7,2) DEFAULT NULL,
  `ss_net_paid` decimal(7,2) DEFAULT NULL,
  `ss_net_paid_inc_tax` decimal(7,2) DEFAULT NULL,
  `ss_net_profit` decimal(7,2) DEFAULT NULL,
  PRIMARY KEY (`ss_item_sk`,`ss_ticket_number`),
  KEY `ss_s` (`ss_store_sk`),
  KEY `ss_t` (`ss_sold_time_sk`),
  KEY `ss_d` (`ss_sold_date_sk`),
  KEY `ss_p` (`ss_promo_sk`),
  KEY `ss_hd` (`ss_hdemo_sk`),
  KEY `ss_c` (`ss_customer_sk`),
  KEY `ss_cd` (`ss_cdemo_sk`),
  KEY `ss_a` (`ss_addr_sk`),
  CONSTRAINT `ss_a` FOREIGN KEY (`ss_addr_sk`) REFERENCES `customer_address` (`ca_address_sk`),
  CONSTRAINT `ss_c` FOREIGN KEY (`ss_customer_sk`) REFERENCES `customer` (`c_customer_sk`),
  CONSTRAINT `ss_cd` FOREIGN KEY (`ss_cdemo_sk`) REFERENCES `customer_demographics` (`cd_demo_sk`),
  CONSTRAINT `ss_d` FOREIGN KEY (`ss_sold_date_sk`) REFERENCES `date_dim` (`d_date_sk`),
  CONSTRAINT `ss_hd` FOREIGN KEY (`ss_hdemo_sk`) REFERENCES `household_demographics` (`hd_demo_sk`),
  CONSTRAINT `ss_i` FOREIGN KEY (`ss_item_sk`) REFERENCES `item` (`i_item_sk`),
  CONSTRAINT `ss_p` FOREIGN KEY (`ss_promo_sk`) REFERENCES `promotion` (`p_promo_sk`),
  CONSTRAINT `ss_s` FOREIGN KEY (`ss_store_sk`) REFERENCES `store` (`s_store_sk`),
  CONSTRAINT `ss_t` FOREIGN KEY (`ss_sold_time_sk`) REFERENCES `time_dim` (`t_time_sk`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `catalog_sales` (
  `cs_sold_date_sk` int DEFAULT NULL,
  `cs_sold_time_sk` int DEFAULT NULL,
  `cs_ship_date_sk` int DEFAULT NULL,
  `cs_bill_customer_sk` int DEFAULT NULL,
  `cs_bill_cdemo_sk` int DEFAULT NULL,
  `cs_bill_hdemo_sk` int DEFAULT NULL,
  `cs_bill_addr_sk` int DEFAULT NULL,
  `cs_ship_customer_sk` int DEFAULT NULL,
  `cs_ship_cdemo_sk` int DEFAULT NULL,
  `cs_ship_hdemo_sk` int DEFAULT NULL,
  `cs_ship_addr_sk` int DEFAULT NULL,
  `cs_call_center_sk` int DEFAULT NULL,
  `cs_catalog_page_sk` int DEFAULT NULL,
  `cs_ship_mode_sk` int DEFAULT NULL,
  `cs_warehouse_sk` int DEFAULT NULL,
  `cs_item_sk` int NOT NULL,
  `cs_promo_sk` int DEFAULT NULL,
  `cs_order_number` int NOT NULL,
  `cs_quantity` int DEFAULT NULL,
  `cs_wholesale_cost` decimal(7,2) DEFAULT NULL,
  `cs_list_price` decimal(7,2) DEFAULT NULL,
  `cs_sales_price` decimal(7,2) DEFAULT NULL,
  `cs_ext_discount_amt` decimal(7,2) DEFAULT NULL,
  `cs_ext_sales_price` decimal(7,2) DEFAULT NULL,
  `cs_ext_wholesale_cost` decimal(7,2) DEFAULT NULL,
  `cs_ext_list_price` decimal(7,2) DEFAULT NULL,
  `cs_ext_tax` decimal(7,2) DEFAULT NULL,
  `cs_coupon_amt` decimal(7,2) DEFAULT NULL,
  `cs_ext_ship_cost` decimal(7,2) DEFAULT NULL,
  `cs_net_paid` decimal(7,2) DEFAULT NULL,
  `cs_net_paid_inc_tax` decimal(7,2) DEFAULT NULL,
  `cs_net_paid_inc_ship` decimal(7,2) DEFAULT NULL,
  `cs_net_paid_inc_ship_tax` decimal(7,2) DEFAULT NULL,
  `cs_net_profit` decimal(7,2) DEFAULT NULL,
  PRIMARY KEY (`cs_item_sk`,`cs_order_number`),
  KEY `cs_w` (`cs_warehouse_sk`),
  KEY `cs_t` (`cs_sold_time_sk`),
  KEY `cs_d2` (`cs_sold_date_sk`),
  KEY `cs_sm` (`cs_ship_mode_sk`),
  KEY `cs_s_hd` (`cs_ship_hdemo_sk`),
  KEY `cs_d1` (`cs_ship_date_sk`),
  KEY `cs_s_c` (`cs_ship_customer_sk`),
  KEY `cs_s_cd` (`cs_ship_cdemo_sk`),
  KEY `cs_s_a` (`cs_ship_addr_sk`),
  KEY `cs_p` (`cs_promo_sk`),
  KEY `cs_cp` (`cs_catalog_page_sk`),
  KEY `cs_cc` (`cs_call_center_sk`),
  KEY `cs_b_hd` (`cs_bill_hdemo_sk`),
  KEY `cs_b_c` (`cs_bill_customer_sk`),
  KEY `cs_b_cd` (`cs_bill_cdemo_sk`),
  KEY `cs_b_a` (`cs_bill_addr_sk`),
  CONSTRAINT `cs_b_a` FOREIGN KEY (`cs_bill_addr_sk`) REFERENCES `customer_address` (`ca_address_sk`),
  CONSTRAINT `cs_b_c` FOREIGN KEY (`cs_bill_customer_sk`) REFERENCES `customer` (`c_customer_sk`),
  CONSTRAINT `cs_b_cd` FOREIGN KEY (`cs_bill_cdemo_sk`) REFERENCES `customer_demographics` (`cd_demo_sk`),
  CONSTRAINT `cs_b_hd` FOREIGN KEY (`cs_bill_hdemo_sk`) REFERENCES `household_demographics` (`hd_demo_sk`),
  CONSTRAINT `cs_cc` FOREIGN KEY (`cs_call_center_sk`) REFERENCES `call_center` (`cc_call_center_sk`),
  CONSTRAINT `cs_cp` FOREIGN KEY (`cs_catalog_page_sk`) REFERENCES `catalog_page` (`cp_catalog_page_sk`),
  CONSTRAINT `cs_d1` FOREIGN KEY (`cs_ship_date_sk`) REFERENCES `date_dim` (`d_date_sk`),
  CONSTRAINT `cs_d2` FOREIGN KEY (`cs_sold_date_sk`) REFERENCES `date_dim` (`d_date_sk`),
  CONSTRAINT `cs_i` FOREIGN KEY (`cs_item_sk`) REFERENCES `item` (`i_item_sk`),
  CONSTRAINT `cs_p` FOREIGN KEY (`cs_promo_sk`) REFERENCES `promotion` (`p_promo_sk`),
  CONSTRAINT `cs_s_a` FOREIGN KEY (`cs_ship_addr_sk`) REFERENCES `customer_address` (`ca_address_sk`),
  CONSTRAINT `cs_s_c` FOREIGN KEY (`cs_ship_customer_sk`) REFERENCES `customer` (`c_customer_sk`),
  CONSTRAINT `cs_s_cd` FOREIGN KEY (`cs_ship_cdemo_sk`) REFERENCES `customer_demographics` (`cd_demo_sk`),
  CONSTRAINT `cs_s_hd` FOREIGN KEY (`cs_ship_hdemo_sk`) REFERENCES `household_demographics` (`hd_demo_sk`),
  CONSTRAINT `cs_sm` FOREIGN KEY (`cs_ship_mode_sk`) REFERENCES `ship_mode` (`sm_ship_mode_sk`),
  CONSTRAINT `cs_t` FOREIGN KEY (`cs_sold_time_sk`) REFERENCES `time_dim` (`t_time_sk`),
  CONSTRAINT `cs_w` FOREIGN KEY (`cs_warehouse_sk`) REFERENCES `warehouse` (`w_warehouse_sk`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `catalog_returns` (
  `cr_returned_date_sk` int DEFAULT NULL,
  `cr_returned_time_sk` int DEFAULT NULL,
  `cr_item_sk` int NOT NULL,
  `cr_refunded_customer_sk` int DEFAULT NULL,
  `cr_refunded_cdemo_sk` int DEFAULT NULL,
  `cr_refunded_hdemo_sk` int DEFAULT NULL,
  `cr_refunded_addr_sk` int DEFAULT NULL,
  `cr_returning_customer_sk` int DEFAULT NULL,
  `cr_returning_cdemo_sk` int DEFAULT NULL,
  `cr_returning_hdemo_sk` int DEFAULT NULL,
  `cr_returning_addr_sk` int DEFAULT NULL,
  `cr_call_center_sk` int DEFAULT NULL,
  `cr_catalog_page_sk` int DEFAULT NULL,
  `cr_ship_mode_sk` int DEFAULT NULL,
  `cr_warehouse_sk` int DEFAULT NULL,
  `cr_reason_sk` int DEFAULT NULL,
  `cr_order_number` int NOT NULL,
  `cr_return_quantity` int DEFAULT NULL,
  `cr_return_amount` decimal(7,2) DEFAULT NULL,
  `cr_return_tax` decimal(7,2) DEFAULT NULL,
  `cr_return_amt_inc_tax` decimal(7,2) DEFAULT NULL,
  `cr_fee` decimal(7,2) DEFAULT NULL,
  `cr_return_ship_cost` decimal(7,2) DEFAULT NULL,
  `cr_refunded_cash` decimal(7,2) DEFAULT NULL,
  `cr_reversed_charge` decimal(7,2) DEFAULT NULL,
  `cr_store_credit` decimal(7,2) DEFAULT NULL,
  `cr_net_loss` decimal(7,2) DEFAULT NULL,
  PRIMARY KEY (`cr_item_sk`,`cr_order_number`),
  KEY `cr_w2` (`cr_warehouse_sk`),
  KEY `cr_sm` (`cr_ship_mode_sk`),
  KEY `cr_hd2` (`cr_returning_hdemo_sk`),
  KEY `cr_c2` (`cr_returning_customer_sk`),
  KEY `cr_cd2` (`cr_returning_cdemo_sk`),
  KEY `cr_a2` (`cr_returning_addr_sk`),
  KEY `cr_t` (`cr_returned_time_sk`),
  KEY `cr_d1` (`cr_returned_date_sk`),
  KEY `cr_hd1` (`cr_refunded_hdemo_sk`),
  KEY `cr_c1` (`cr_refunded_customer_sk`),
  KEY `cr_cd1` (`cr_refunded_cdemo_sk`),
  KEY `cr_a1` (`cr_refunded_addr_sk`),
  KEY `cr_r` (`cr_reason_sk`),
  KEY `cr_cp` (`cr_catalog_page_sk`),
  KEY `cr_cc` (`cr_call_center_sk`),
  CONSTRAINT `cr_a1` FOREIGN KEY (`cr_refunded_addr_sk`) REFERENCES `customer_address` (`ca_address_sk`),
  CONSTRAINT `cr_a2` FOREIGN KEY (`cr_returning_addr_sk`) REFERENCES `customer_address` (`ca_address_sk`),
  CONSTRAINT `cr_c1` FOREIGN KEY (`cr_refunded_customer_sk`) REFERENCES `customer` (`c_customer_sk`),
  CONSTRAINT `cr_c2` FOREIGN KEY (`cr_returning_customer_sk`) REFERENCES `customer` (`c_customer_sk`),
  CONSTRAINT `cr_cc` FOREIGN KEY (`cr_call_center_sk`) REFERENCES `call_center` (`cc_call_center_sk`),
  CONSTRAINT `cr_cd1` FOREIGN KEY (`cr_refunded_cdemo_sk`) REFERENCES `customer_demographics` (`cd_demo_sk`),
  CONSTRAINT `cr_cd2` FOREIGN KEY (`cr_returning_cdemo_sk`) REFERENCES `customer_demographics` (`cd_demo_sk`),
  CONSTRAINT `cr_cp` FOREIGN KEY (`cr_catalog_page_sk`) REFERENCES `catalog_page` (`cp_catalog_page_sk`),
  CONSTRAINT `cr_d1` FOREIGN KEY (`cr_returned_date_sk`) REFERENCES `date_dim` (`d_date_sk`),
  CONSTRAINT `cr_hd1` FOREIGN KEY (`cr_refunded_hdemo_sk`) REFERENCES `household_demographics` (`hd_demo_sk`),
  CONSTRAINT `cr_hd2` FOREIGN KEY (`cr_returning_hdemo_sk`) REFERENCES `household_demographics` (`hd_demo_sk`),
  CONSTRAINT `cr_i` FOREIGN KEY (`cr_item_sk`) REFERENCES `item` (`i_item_sk`),
  CONSTRAINT `cr_r` FOREIGN KEY (`cr_reason_sk`) REFERENCES `reason` (`r_reason_sk`),
  CONSTRAINT `cr_sm` FOREIGN KEY (`cr_ship_mode_sk`) REFERENCES `ship_mode` (`sm_ship_mode_sk`),
  CONSTRAINT `cr_t` FOREIGN KEY (`cr_returned_time_sk`) REFERENCES `time_dim` (`t_time_sk`),
  CONSTRAINT `cr_w2` FOREIGN KEY (`cr_warehouse_sk`) REFERENCES `warehouse` (`w_warehouse_sk`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `web_page` (
  `wp_web_page_sk` int(11) NOT NULL,
  `wp_web_page_id` char(16) NOT NULL,
  `wp_rec_start_date` date DEFAULT NULL,
  `wp_rec_end_date` date DEFAULT NULL,
  `wp_creation_date_sk` int(11) DEFAULT NULL,
  `wp_access_date_sk` int(11) DEFAULT NULL,
  `wp_autogen_flag` char(1) DEFAULT NULL,
  `wp_customer_sk` int(11) DEFAULT NULL,
  `wp_url` varchar(100) DEFAULT NULL,
  `wp_type` char(50) DEFAULT NULL,
  `wp_char_count` int(11) DEFAULT NULL,
  `wp_link_count` int(11) DEFAULT NULL,
  `wp_image_count` int(11) DEFAULT NULL,
  `wp_max_ad_count` int(11) DEFAULT NULL,
  PRIMARY KEY (`wp_web_page_sk`),
  KEY `wp_cd` (`wp_creation_date_sk`),
  KEY `wp_ad` (`wp_access_date_sk`),
  CONSTRAINT `wp_ad` FOREIGN KEY (`wp_access_date_sk`) REFERENCES `date_dim` (`d_date_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `wp_cd` FOREIGN KEY (`wp_creation_date_sk`) REFERENCES `date_dim` (`d_date_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `web_returns` (
  `wr_returned_date_sk` int(11) DEFAULT NULL,
  `wr_returned_time_sk` int(11) DEFAULT NULL,
  `wr_item_sk` int(11) NOT NULL,
  `wr_refunded_customer_sk` int(11) DEFAULT NULL,
  `wr_refunded_cdemo_sk` int(11) DEFAULT NULL,
  `wr_refunded_hdemo_sk` int(11) DEFAULT NULL,
  `wr_refunded_addr_sk` int(11) DEFAULT NULL,
  `wr_returning_customer_sk` int(11) DEFAULT NULL,
  `wr_returning_cdemo_sk` int(11) DEFAULT NULL,
  `wr_returning_hdemo_sk` int(11) DEFAULT NULL,
  `wr_returning_addr_sk` int(11) DEFAULT NULL,
  `wr_web_page_sk` int(11) DEFAULT NULL,
  `wr_reason_sk` int(11) DEFAULT NULL,
  `wr_order_number` int(11) NOT NULL,
  `wr_return_quantity` int(11) DEFAULT NULL,
  `wr_return_amt` decimal(7,2) DEFAULT NULL,
  `wr_return_tax` decimal(7,2) DEFAULT NULL,
  `wr_return_amt_inc_tax` decimal(7,2) DEFAULT NULL,
  `wr_fee` decimal(7,2) DEFAULT NULL,
  `wr_return_ship_cost` decimal(7,2) DEFAULT NULL,
  `wr_refunded_cash` decimal(7,2) DEFAULT NULL,
  `wr_reversed_charge` decimal(7,2) DEFAULT NULL,
  `wr_account_credit` decimal(7,2) DEFAULT NULL,
  `wr_net_loss` decimal(7,2) DEFAULT NULL,
  PRIMARY KEY (`wr_item_sk`,`wr_order_number`),
  KEY `wr_wp` (`wr_web_page_sk`),
  KEY `wr_ret_hd` (`wr_returning_hdemo_sk`),
  KEY `wr_ret_c` (`wr_returning_customer_sk`),
  KEY `wr_ret_cd` (`wr_returning_cdemo_sk`),
  KEY `wr_ret_a` (`wr_returning_addr_sk`),
  KEY `wr_ret_t` (`wr_returned_time_sk`),
  KEY `wr_ret_d` (`wr_returned_date_sk`),
  KEY `wr_ref_hd` (`wr_refunded_hdemo_sk`),
  KEY `wr_ref_c` (`wr_refunded_customer_sk`),
  KEY `wr_ref_cd` (`wr_refunded_cdemo_sk`),
  KEY `wr_ref_a` (`wr_refunded_addr_sk`),
  KEY `wr_r` (`wr_reason_sk`),
  CONSTRAINT `wr_i` FOREIGN KEY (`wr_item_sk`) REFERENCES `item` (`i_item_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `wr_r` FOREIGN KEY (`wr_reason_sk`) REFERENCES `reason` (`r_reason_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `wr_ref_a` FOREIGN KEY (`wr_refunded_addr_sk`) REFERENCES `customer_address` (`ca_address_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `wr_ref_c` FOREIGN KEY (`wr_refunded_customer_sk`) REFERENCES `customer` (`c_customer_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `wr_ref_cd` FOREIGN KEY (`wr_refunded_cdemo_sk`) REFERENCES `customer_demographics` (`cd_demo_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `wr_ref_hd` FOREIGN KEY (`wr_refunded_hdemo_sk`) REFERENCES `household_demographics` (`hd_demo_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `wr_ret_a` FOREIGN KEY (`wr_returning_addr_sk`) REFERENCES `customer_address` (`ca_address_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `wr_ret_c` FOREIGN KEY (`wr_returning_customer_sk`) REFERENCES `customer` (`c_customer_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `wr_ret_cd` FOREIGN KEY (`wr_returning_cdemo_sk`) REFERENCES `customer_demographics` (`cd_demo_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `wr_ret_d` FOREIGN KEY (`wr_returned_date_sk`) REFERENCES `date_dim` (`d_date_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `wr_ret_hd` FOREIGN KEY (`wr_returning_hdemo_sk`) REFERENCES `household_demographics` (`hd_demo_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `wr_ret_t` FOREIGN KEY (`wr_returned_time_sk`) REFERENCES `time_dim` (`t_time_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `wr_wp` FOREIGN KEY (`wr_web_page_sk`) REFERENCES `web_page` (`wp_web_page_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `web_site` (
  `web_site_sk` int(11) NOT NULL,
  `web_site_id` char(16) NOT NULL,
  `web_rec_start_date` date DEFAULT NULL,
  `web_rec_end_date` date DEFAULT NULL,
  `web_name` varchar(50) DEFAULT NULL,
  `web_open_date_sk` int(11) DEFAULT NULL,
  `web_close_date_sk` int(11) DEFAULT NULL,
  `web_class` varchar(50) DEFAULT NULL,
  `web_manager` varchar(40) DEFAULT NULL,
  `web_mkt_id` int(11) DEFAULT NULL,
  `web_mkt_class` varchar(50) DEFAULT NULL,
  `web_mkt_desc` varchar(100) DEFAULT NULL,
  `web_market_manager` varchar(40) DEFAULT NULL,
  `web_company_id` int(11) DEFAULT NULL,
  `web_company_name` char(50) DEFAULT NULL,
  `web_street_number` char(10) DEFAULT NULL,
  `web_street_name` varchar(60) DEFAULT NULL,
  `web_street_type` char(15) DEFAULT NULL,
  `web_suite_number` char(10) DEFAULT NULL,
  `web_city` varchar(60) DEFAULT NULL,
  `web_county` varchar(30) DEFAULT NULL,
  `web_state` char(2) DEFAULT NULL,
  `web_zip` char(10) DEFAULT NULL,
  `web_country` varchar(20) DEFAULT NULL,
  `web_gmt_offset` decimal(5,2) DEFAULT NULL,
  `web_tax_percentage` decimal(5,2) DEFAULT NULL,
  PRIMARY KEY (`web_site_sk`),
  KEY `web_d2` (`web_open_date_sk`),
  KEY `web_d1` (`web_close_date_sk`),
  CONSTRAINT `web_d1` FOREIGN KEY (`web_close_date_sk`) REFERENCES `date_dim` (`d_date_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `web_d2` FOREIGN KEY (`web_open_date_sk`) REFERENCES `date_dim` (`d_date_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `web_sales` (
  `ws_sold_date_sk` int(11) DEFAULT NULL,
  `ws_sold_time_sk` int(11) DEFAULT NULL,
  `ws_ship_date_sk` int(11) DEFAULT NULL,
  `ws_item_sk` int(11) NOT NULL,
  `ws_bill_customer_sk` int(11) DEFAULT NULL,
  `ws_bill_cdemo_sk` int(11) DEFAULT NULL,
  `ws_bill_hdemo_sk` int(11) DEFAULT NULL,
  `ws_bill_addr_sk` int(11) DEFAULT NULL,
  `ws_ship_customer_sk` int(11) DEFAULT NULL,
  `ws_ship_cdemo_sk` int(11) DEFAULT NULL,
  `ws_ship_hdemo_sk` int(11) DEFAULT NULL,
  `ws_ship_addr_sk` int(11) DEFAULT NULL,
  `ws_web_page_sk` int(11) DEFAULT NULL,
  `ws_web_site_sk` int(11) DEFAULT NULL,
  `ws_ship_mode_sk` int(11) DEFAULT NULL,
  `ws_warehouse_sk` int(11) DEFAULT NULL,
  `ws_promo_sk` int(11) DEFAULT NULL,
  `ws_order_number` int(11) NOT NULL,
  `ws_quantity` int(11) DEFAULT NULL,
  `ws_wholesale_cost` decimal(7,2) DEFAULT NULL,
  `ws_list_price` decimal(7,2) DEFAULT NULL,
  `ws_sales_price` decimal(7,2) DEFAULT NULL,
  `ws_ext_discount_amt` decimal(7,2) DEFAULT NULL,
  `ws_ext_sales_price` decimal(7,2) DEFAULT NULL,
  `ws_ext_wholesale_cost` decimal(7,2) DEFAULT NULL,
  `ws_ext_list_price` decimal(7,2) DEFAULT NULL,
  `ws_ext_tax` decimal(7,2) DEFAULT NULL,
  `ws_coupon_amt` decimal(7,2) DEFAULT NULL,
  `ws_ext_ship_cost` decimal(7,2) DEFAULT NULL,
  `ws_net_paid` decimal(7,2) DEFAULT NULL,
  `ws_net_paid_inc_tax` decimal(7,2) DEFAULT NULL,
  `ws_net_paid_inc_ship` decimal(7,2) DEFAULT NULL,
  `ws_net_paid_inc_ship_tax` decimal(7,2) DEFAULT NULL,
  `ws_net_profit` decimal(7,2) DEFAULT NULL,
  PRIMARY KEY (`ws_item_sk`,`ws_order_number`),
  KEY `ws_ws` (`ws_web_site_sk`),
  KEY `ws_wp` (`ws_web_page_sk`),
  KEY `ws_w2` (`ws_warehouse_sk`),
  KEY `ws_t` (`ws_sold_time_sk`),
  KEY `ws_d2` (`ws_sold_date_sk`),
  KEY `ws_sm` (`ws_ship_mode_sk`),
  KEY `ws_s_hd` (`ws_ship_hdemo_sk`),
  KEY `ws_s_d` (`ws_ship_date_sk`),
  KEY `ws_s_c` (`ws_ship_customer_sk`),
  KEY `ws_s_cd` (`ws_ship_cdemo_sk`),
  KEY `ws_s_a` (`ws_ship_addr_sk`),
  KEY `ws_p` (`ws_promo_sk`),
  KEY `ws_b_hd` (`ws_bill_hdemo_sk`),
  KEY `ws_b_c` (`ws_bill_customer_sk`),
  KEY `ws_b_cd` (`ws_bill_cdemo_sk`),
  KEY `ws_b_a` (`ws_bill_addr_sk`),
  CONSTRAINT `ws_b_a` FOREIGN KEY (`ws_bill_addr_sk`) REFERENCES `customer_address` (`ca_address_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ws_b_c` FOREIGN KEY (`ws_bill_customer_sk`) REFERENCES `customer` (`c_customer_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ws_b_cd` FOREIGN KEY (`ws_bill_cdemo_sk`) REFERENCES `customer_demographics` (`cd_demo_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ws_b_hd` FOREIGN KEY (`ws_bill_hdemo_sk`) REFERENCES `household_demographics` (`hd_demo_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ws_d2` FOREIGN KEY (`ws_sold_date_sk`) REFERENCES `date_dim` (`d_date_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ws_i` FOREIGN KEY (`ws_item_sk`) REFERENCES `item` (`i_item_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ws_p` FOREIGN KEY (`ws_promo_sk`) REFERENCES `promotion` (`p_promo_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ws_s_a` FOREIGN KEY (`ws_ship_addr_sk`) REFERENCES `customer_address` (`ca_address_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ws_s_c` FOREIGN KEY (`ws_ship_customer_sk`) REFERENCES `customer` (`c_customer_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ws_s_cd` FOREIGN KEY (`ws_ship_cdemo_sk`) REFERENCES `customer_demographics` (`cd_demo_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ws_s_d` FOREIGN KEY (`ws_ship_date_sk`) REFERENCES `date_dim` (`d_date_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ws_s_hd` FOREIGN KEY (`ws_ship_hdemo_sk`) REFERENCES `household_demographics` (`hd_demo_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ws_sm` FOREIGN KEY (`ws_ship_mode_sk`) REFERENCES `ship_mode` (`sm_ship_mode_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ws_t` FOREIGN KEY (`ws_sold_time_sk`) REFERENCES `time_dim` (`t_time_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ws_w2` FOREIGN KEY (`ws_warehouse_sk`) REFERENCES `warehouse` (`w_warehouse_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ws_wp` FOREIGN KEY (`ws_web_page_sk`) REFERENCES `web_page` (`wp_web_page_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `ws_ws` FOREIGN KEY (`ws_web_site_sk`) REFERENCES `web_site` (`web_site_sk`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


